spring.application.name=event-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/event_db
spring.datasource.username=root
spring.datasource.password=123456aksh987

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=59917dc372139385e5bd83ac46b553096f6617637dc07fe265b5f70575c37041
